version: '4.8.1'
services:
  db:
    image: mysql
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?error}
      MYSQL_DATABASE: nickeljar
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
    ports:
      - "9906:3306"
  client:
    build: .
    depends_on:
      - db
    volumes:
      - ./server:/app/data:rw
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN:?error}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
