version: '4.8.1'
services:
  db:
    image: mysql
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?error}
      MYSQL_DATABASE: nickeljar
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
    ports:
      - "9906:3306"
  client:
    build: .
    depends_on:
      - db
    ports:
      - 8080
    volumes:
      - ./server:/app/data:rw
  # security:
  #   build: ./security
  #   depends_on:
  #     - client
  #   ports:
  #     - 443:443